import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronDown, CircleHelp, Heart, LockKeyhole, Menu, PackageCheck, Pause, Play, Plus, Printer, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import './style.css';

type Slide = { kicker: string; title: React.ReactNode; body: React.ReactNode; visual: React.ReactNode; note?: string };
const fmt = (n:number) => new Intl.NumberFormat('ja-JP').format(Math.round(n));

function CollectionDemo(){
 const [step,setStep]=useState(0),[offer,setOffer]=useState(false),[price,setPrice]=useState(1800),[done,setDone]=useState(false);
 return <div className="demo-window"><div className="demo-top"><span className="window-dots"><i/><i/><i/></span><span>my collection</span><span className="demo-tag">モック</span></div><div className="demo-body">
 <div className="demo-heading"><div><small>COLLECTION / 12</small><h3>だいすきなもの</h3></div><button className="circle-btn" aria-label="コレクションに追加"><Plus size={17}/></button></div>
 <div className="objects"><button className={`object object-main ${step===1?'muted':''}`} onClick={()=>setStep(step===1?0:1)} aria-label="展示品の設定"><span className="obj-art plush"><span className="plush-face">•ᴗ•</span></span><span className="object-caption">おでかけマスコット</span><span className="object-state">{step===1?'展示のみ':'コレクション'}</span></button><button className={`object object-small ${offer?'selected':''}`} onClick={()=>{setOffer(!offer);setDone(false)}} aria-label="購入希望受付の切り替え"><span className="obj-art charm"><Heart size={25}/><i>✳</i></span><span className="object-caption">レトロチャーム</span><span className="object-state">{offer?'希望を受付中':'手元に置いておく'}</span></button></div>
 <div className="permission-note"><LockKeyhole size={14}/><span>公開・希望受付・譲渡承認は、それぞれ自分で決められます。</span></div>
 {offer&&<motion.div className="offer-panel" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><div className="offer-title"><span><Sparkles size={14}/> ほしい人がいます</span><small>条件を確認</small></div><p>「ずっと探していました。状態と送料を見て検討したいです」</p><div className="price-line"><span>希望価格の目安</span><strong>¥{fmt(price)}</strong></div><input aria-label="希望価格の調整" type="range" min="500" max="5000" step="100" value={price} onChange={e=>setPrice(Number(e.target.value))}/><div className="offer-actions"><button onClick={()=>setOffer(false)}>今回は見送る</button><button className="accept" onClick={()=>setDone(true)}>{done?<><Check size={14}/> 希望を受け取りました</>:'詳しい条件を確認'}</button></div>{done&&<small className="success-msg">まだ取引は成立していません。最後の譲渡承認は持ち主が決めます。</small>}</motion.div>}
 <div className="demo-legend"><span><i className="dot lilac"/>展示だけ</span><span><i className="dot coral"/>希望受付は任意</span><span><i className="dot gray"/>成約前に条件確認</span></div>
 </div><div className="demo-footer"><span>サンプル画面・購入や送信は行いません</span><button onClick={()=>setOffer(!offer)}>{offer?'表示を閉じる':'購入希望を見てみる'} <ArrowRight size={14}/></button></div></div>
}

function Calculator(){
 const [buyers,setBuyers]=useState(1000),[frequency,setFrequency]=useState(2),[basket,setBasket]=useState(3000),[rate,setRate]=useState(12),[cost,setCost]=useState(9000000);
 const trades=buyers*frequency, gmv=trades*basket, revenue=gmv*rate/100, profit=revenue-cost;
 const rows=[['購入者数',buyers,setBuyers,'人'],['年取引回数',frequency,setFrequency,'回'],['平均取引額',basket,setBasket,'円'],['手数料率',rate,setRate,'%'] ] as const;
 return <div className="calc"><div className="calc-controls">{rows.map(([label,val,set,unit])=><label className="calc-row" key={label}><span>{label}<b>{fmt(val)}{unit}</b></span><input aria-label={label} type="range" min={label==='購入者数'?100:label==='年取引回数'?1:label==='平均取引額'?500:3} max={label==='購入者数'?10000:label==='年取引回数'?12:label==='平均取引額'?20000:25} step={label==='購入者数'?100:label==='年取引回数'?1:label==='平均取引額'?500:1} value={val} onChange={e=>set(Number(e.target.value))}/></label>)}<label className="cost-row">年間変動費・集客費などの仮置き<input type="number" min="0" step="100000" value={cost} onChange={e=>setCost(Number(e.target.value))}/><span>円</span></label></div><div className="calc-output"><div className="result-label"><span>年の取引総額</span><b>¥{fmt(gmv)}</b></div><div className="result-label"><span>手数料売上</span><b>¥{fmt(revenue)}</b></div><div className={`result-profit ${profit<0?'negative':''}`}><span>費用控除後の試算</span><b>{profit<0?'−':''}¥{fmt(Math.abs(profit))}</b><small>{profit>=0?'固定費・税等を除く概算':'仮置き費用を回収できない試算'}</small></div><div className="formula">購入者 × 頻度 × 取引額 × 手数料率 − 費用</div></div><p className="calc-caveat">青い数値は全て仮定です。決済・検品・梱包配送・補償・問い合わせ・集客・固定費を実測し、成立率と再購入を確かめます。</p></div>
}

const sources=[
 ['サンリオ公式オンラインショップ｜ご利用上の注意','https://shop.sanrio.co.jp/guide/notes','転売目的の大量購入を控える案内。該当注文をキャンセルする場合がある。正規品中古取引全般の禁止を示す資料ではない。'],
 ['環境省｜リユースの促進','https://www.env.go.jp/recycle/circul/reuse/','リユースによる使用期間長期化などの一般論。今回サービスの環境効果は未計測。'],
 ['国民生活センター｜フリマサービスの偽物・すり替え注意','https://www.kokusen.go.jp/news/data/n-20250902_2.html','一般フリマの相談事例。サンリオ商品の発生率を示す資料ではない。'],
 ['スニーカーダンク｜コレクションについて','https://help.snkrdunk-guide.com/ja/articles/コレクションについて-2a835377','所持品の管理から出品・オファー承諾が可能。'],
 ['スニーカーダンク｜オファー','https://help.snkrdunk-guide.com/ja/articles/オファー-868427cd','案内上、オファー対象は新品。今回案と一致するサービスではない。'],
 ['Yahoo!オークション × minikura','https://auctions.yahoo.co.jp/topic/promo/minikura/','保管品の出品と倉庫梱包発送の連携例。掲載される旧料金を現行価格として扱わない。'],
 ['サマリーポケット｜推し活グッズ収納の利用例','https://pocket.sumally.com/journal/2022/01/28/otaku_goods_syunou/','事業者が紹介する個別例。サンリオファン全体の需要を示さない。'],
 ['警視庁｜古物商許可申請','https://www.keishicho.metro.tokyo.lg.jp/tetsuzuki/kobutsu/kaisetsu/kobutsu_shinsei.html','本人確認等は事業形態に応じて確認。案の適法性は未判定。'],
 ['国土交通省｜倉庫業法について','https://www.mlit.go.jp/seisakutokatsu/freight/butsuryu05100.html','有料保管を行う場合の登録等は営業形態ごとに確認する。'],
 ['RoomClip｜ルームコレクション','https://roomclip.jp/shopping/about','写真共有から商品リンクにつなぐ先行例。'],
 ['Sanrio｜知的財産の案内（米国向け）','https://www.sanrio.com/pages/sanrio-intellectual-property-info','新規商品制作・宣伝等の権利説明。日本の真正中古品全般を禁止する資料として使わない。']
];

function App(){
 const [slide,setSlide]=useState(0),[mode,setMode]=useState<'pitch'|'read'>('pitch'),[paused,setPaused]=useState(false),[menu,setMenu]=useState(false);
 const slides:Slide[]=useMemo(()=>[
 {kicker:'NEW BUSINESS / 日本トレカセンター',title:<>手放してもいい日が<br/><em>来たら。</em></>,body:<>探している人と、条件次第で譲れる人をつなぐ。<br/>コレクションの楽しみから始める、ファン向け二次流通の提案。</>,visual:<div className="hero-art"><div className="halo"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><span className="spark s1">✳</span><span className="spark s2">✦</span><div className="hero-object object-coral"><span>◌</span></div><div className="hero-object object-violet"><span>♡</span></div><div className="hero-object object-sand"><span>✳</span></div><div className="hero-label"><small>THE IDEA</small><span>好きな気持ちが<br/>次の人へつながる</span></div></div>,note:'CEO向け提案｜5分｜事業仮説と検証案'},
 {kicker:'01 / WHO & WHY',title:<>探す人はいる。<br/><em>譲れる人もいる。</em></>,body:<>既存の売り場やSNSで出品を探しても、未出品の品は見つけられません。条件次第で譲れる所有品があるかも未確認です。<br/><b>同じ品・条件で、双方が動くか。</b>そこから確かめます。</>,visual:<div className="match-visual"><div className="person buyer"><span className="avatar">⌕</span><small>探しているファン</small><strong>「この柄が<br/>見つからない」</strong><span className="tiny-pill">品を特定して探す</span></div><div className="match-center"><span className="thread t1"/><span className="thread t2"/><div className="match-star">✳</div><small>品 × 条件</small></div><div className="person owner"><span className="avatar">♡</span><small>条件次第で譲れる人</small><strong>「大切だから<br/>納得して決めたい」</strong><span className="tiny-pill">公開も受付も任意</span></div><span className="visual-caption">需要と供給が重なるかは未検証</span></div>,note:'課題仮説：既存売り場や出品から見つからない商品がある。需要と供給が同じ商品・条件で交わる必要がある。'},
 {kicker:'02 / THE VALUE',title:<>手放す選択も、<br/><em>手元に置く選択も。</em></>,body:<>買い手には入手機会を。所有者には自分で決められる選択肢を。品物には次の人が楽しむ機会を。<br/><b>売らない選択も、サービスが尊重します。</b></>,visual:<div className="value-visual"><div className="value-route"><div className="value-node"><span className="vn-art">✿</span><small>持ち主のコレクション</small></div><div className="route-line"><i/><i/><i/></div><div className="value-choice"><div className="choice-card keep"><span>♡</span><b>持ち続ける</b><small>展示だけ・非公開</small></div><div className="choice-card next"><span>↗</span><b>次の人へ</b><small>条件が合えば譲渡</small></div></div><div className="route-line route-end"><i/><i/><i/></div><div className="value-node receiver"><span className="vn-art">☺</span><small>探していたファン</small></div></div><div className="value-note"><ShieldCheck size={17}/><span>状態・送料・手数料を見える形に。新商品の買い占めを促さない。</span></div><small className="env-note">リユースの一般的な意義はあるが、このサービスの環境効果は未計測。</small></div>,note:'価値は取引のあり方で生まれる。公式の転売目的大量購入への案内を踏まえ、新商品買い占めを促さない。'},
 {kicker:'03 / THE EXPERIENCE',title:<>見せる。受け付ける。<br/><em>最後は自分で決める。</em></>,body:<>コレクションを記録し、公開範囲を選択。譲渡可能な品だけ希望を受け付け、条件を見てから合意します。<br/><b>展示と売却の意思を切り分けます。</b></>,visual:<CollectionDemo/>,note:'本画面は体験モック。実購入・決済・データ送信は行わない。'},
 {kicker:'04 / BUSINESS MODEL',title:<>まずは、有償取引の<br/><em>成立手数料。</em></>,body:<>利用者の取引総額が、そのまま当社売上になるわけではありません。成立した取引から手数料を受け取り、運用費用を差し引いて採算を見ます。</>,visual:<Calculator/>,note:'全て仮定の試算。変動費・獲得費・固定費を確認後、実測値に置き換える。'},
 {kicker:'05 / WHY JTCC',title:<>既存の強みを、<br/><em>確かめてから活かす。</em></>,body:<>物流・真贋・調達・集客などに活用できる資産があるかは社内確認が必要です。日本IPのファン取引を学び、次のIPや地域へ広げられる事業基盤を探ります。</>,visual:<div className="capability"><div className="cap-hub"><small>日本トレカセンター</small><strong>ファン向け<br/>取引体験</strong><span>仮説検証の起点</span></div><div className="cap-links"><div><PackageCheck/><b>物流・梱包</b><small>既存能力と余力を確認</small></div><div><ShieldCheck/><b>真贋・状態</b><small>商材ごとの検品設計</small></div><div><Search/><b>顧客接点</b><small>獲得経路と費用を確認</small></div></div><div className="cap-caveat"><CircleHelp size={15}/>サンリオファンが既存顧客にいるか、権利者が歓迎するかは未確認</div></div>,note:'既存の物流・真贋・調達・集客能力を保有すると断言せず、利用可能性を検証する。公式提携・独占契約・IP利用許諾は別の論点。'},
 {kicker:'06 / VALIDATE',title:<>最初の一歩は、<br/><em>狭く、確かに。</em></>,body:<>サンリオの具体的な商品群を絞り、「欲しい人」「譲れる人」「条件」「有償取引」「採算」が一つの品でそろうかを検証します。</>,visual:<div className="roadmap"><div className="road-step"><span>01</span><small>品を絞る</small><b>商品群・状態・<br/>取引条件を定義</b><i>範囲は小さく始める</i></div><div className="road-step active"><span>02</span><small>一致を測る</small><b>購入意思と<br/>譲渡意思を確認</b><i>送料込みの意思まで聞く</i></div><div className="road-step"><span>03</span><small>採算を測る</small><b>成立・再購入・<br/>運用費を記録</b><i>拡大判断を数字で行う</i></div><div className="road-gate"><span>GATE</span><b>需給一致 × 有償成約 × 採算</b><small>通過後に、対象品・地域・保管機能を判断</small></div><div className="road-footer">海外人気は海外売上の予測ではありません。日本から海外販売・海外保管・海外CtoCは個別に検証します。</div></div>,note:'初期検証の終了条件、商品群、対象国は未決定。日本の中古品取引、古物営業、個人情報、規約、知財・商標等は実装前に確認。'}
 ],[]);
 const count=slides.length;
 const go=(n:number)=>{const next=(n+count)%count; setSlide(next);history.replaceState(null,'',`#slide-${next+1}`)};
 useEffect(()=>{const ix=Number(location.hash.match(/slide-(\d+)/)?.[1]);if(ix>0&&ix<=count)setSlide(ix-1);const fn=(e:KeyboardEvent)=>{if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();go(slide+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(slide-1)}if(e.key==='Escape'){setMode('read');setMenu(false)}if(e.key==='Home')go(0);if(e.key==='End')go(count-1)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[slide,count]);
 useEffect(()=>{document.body.classList.toggle('reading',mode==='read');return()=>document.body.classList.remove('reading')},[mode]);
 const toggleMode=()=>{setMode(mode==='pitch'?'read':'pitch')};
 return <div className={`app ${mode==='read'?'read-mode':''}`}><header className="topbar"><a className="brand" href="#slide-1" onClick={e=>{e.preventDefault();go(0)}}><span className="brand-mark">jt</span><span>日本トレカセンター<small>NEW BUSINESS PITCH</small></span></a><nav><button className={mode==='pitch'?'nav-active':''} onClick={()=>setMode('pitch')}>発表</button><button className={mode==='read'?'nav-active':''} onClick={()=>setMode('read')}>閲覧</button><button className="appendix-nav" onClick={()=>{setMode('read');document.getElementById('appendix')?.scrollIntoView({behavior:'smooth'})}}>補足・出典 <ChevronDown size={14}/></button></nav><div className="top-actions"><button className="icon-btn print-btn" onClick={()=>window.print()} aria-label="印刷"><Printer size={17}/></button><button className="present-btn" onClick={toggleMode}>{mode==='pitch'?<><Play size={14} fill="currentColor"/> 発表モード</>:<>閲覧モード</>}</button><button className="icon-btn menu-btn" onClick={()=>setMenu(!menu)} aria-label="メニュー">{menu?<X size={18}/>:<Menu size={18}/>}</button></div></header>
 {menu&&<div className="mobile-menu"><button onClick={()=>{setMode('pitch');setMenu(false)}}>発表モード</button><button onClick={()=>{setMode('read');setMenu(false)}}>閲覧モード</button><button onClick={()=>{setMode('read');setMenu(false);setTimeout(()=>document.getElementById('appendix')?.scrollIntoView({behavior:'smooth'}),50)}}>補足・出典</button></div>}
 <main className={mode==='pitch'?'presentation':'reader reader-active'}><AnimatePresence mode="wait"><motion.section key={slide} className={`slide slide-${slide+1}`} initial={mode==='pitch'?{opacity:0,y:16}:{opacity:1}} animate={{opacity:1,y:0}} exit={mode==='pitch'?{opacity:0,y:-12}:{opacity:1}} transition={{duration:.38,ease:[.22,1,.36,1]}}><div className="slide-copy"><div className="kicker"><span>{slides[slide].kicker}</span><i/></div><h1>{slides[slide].title}</h1><p className="slide-body">{slides[slide].body}</p>{slides[slide].note&&<div className="slide-note"><i/> {slides[slide].note}</div>}{slide===0&&<button className="start-link" onClick={()=>go(1)}>提案を見る <ArrowDown size={15}/></button>}</div><div className="slide-visual">{slides[slide].visual}</div><span className="slide-index">{String(slide+1).padStart(2,'0')} <i/> 07</span></motion.section></AnimatePresence>
 {mode==='pitch'&&<><div className="present-controls"><button onClick={()=>go(slide-1)} aria-label="前のスライド"><ArrowLeft size={16}/></button><div className="progress-track">{slides.map((_,i)=><button key={i} aria-label={`${i+1}枚目へ`} className={i===slide?'current':''} onClick={()=>go(i)}/>)}</div><button onClick={()=>go(slide+1)} aria-label="次のスライド"><ArrowRight size={16}/></button><span className="key-hint">← →</span></div><button className="pause-btn" onClick={()=>setPaused(!paused)} title="自動進行はありません"><Pause size={13}/><span>自動進行なし</span></button></>}</main>
 {mode==='read'&&<><div className="reader-controls"><button onClick={()=>{const target=(slide-1+count)%count;go(target);document.getElementById('read-slide-'+target)?.scrollIntoView({behavior:'smooth'})}}><ArrowLeft size={15}/> 前へ</button><div>{slides.map((_,i)=><button key={i} className={i===slide?'current':''} onClick={()=>{go(i);document.getElementById('read-slide-'+i)?.scrollIntoView({behavior:'smooth'})}}>{String(i+1).padStart(2,'0')}</button>)}</div><button onClick={()=>{const target=(slide+1)%count;go(target);document.getElementById('read-slide-'+target)?.scrollIntoView({behavior:'smooth'})}}>次へ <ArrowRight size={15}/></button></div>{slides.map((s,i)=><section key={i} id={`read-slide-${i}`} className={`reader-slide slide slide-${i+1}`}><div className="slide-copy"><div className="kicker"><span>{s.kicker}</span><i/></div><h1>{s.title}</h1><p className="slide-body">{s.body}</p>{s.note&&<div className="slide-note"><i/> {s.note}</div>}</div><div className="slide-visual">{s.visual}</div><span className="slide-index">{String(i+1).padStart(2,"0")} <i/> 07</span></section>)}<section className="appendix" id="appendix"><div className="appendix-head"><div><span className="kicker-text">SUPPORTING NOTES</span><h2>補足と確認事項</h2></div><span className="appendix-label">仮説・未決事項・出典</span></div><div className="appendix-grid"><article className="appendix-card"><span>01 / 検証したいこと</span><ul><li>手放さない理由は、不安・愛着・価格・出品の手間のどれか。</li><li>譲れる品と欲しい品は一致するか。希少品ほど譲られにくい可能性。</li><li>「欲しい」という反応が、送料・手数料込みの購入意思になるか。</li><li>SNSから登録する理由と、買い手・売り手双方の獲得費用。</li><li>直取引、売れ残り、識別・状態説明、補償、問い合わせのコスト。</li></ul></article><article className="appendix-card"><span>02 / 事業設計の論点</span><ul><li>初期に解く課題は供給・探索・信頼のどれか。現案は未出品品への任意受付。</li><li>売買・交換・無償譲渡は動機と収益が異なる。有償売買の成立手数料から検証。</li><li>保管は譲渡動機を下げる可能性があるため初期必須にしない。</li><li>二次流通、IP許諾、公式提携、独占契約は別論点。形態ごとに法務確認。</li><li>再転売防止や本当のファンへの到達は保証できない。サンリオの歓迎も未確認。</li></ul></article><article className="appendix-card"><span>03 / 拡大の前提</span><ul><li>初期商品群、検証の終了条件、対象国は未決定。</li><li>日本から海外販売、海外保管、海外CtoCは異なる運用・規制・費用が必要。</li><li>海外人気、年齢構成、女性比率、市場規模、平均購入額は本資料で仮定しない。</li><li>提供されたVlog 3本の分析は一次動画URL未共有のため、利用シーンに関する仮説に限定。</li><li>¥62,206の特別な買い物例は、平均客単価として使わない。</li></ul></article></div><div className="source-section"><div className="source-heading"><h3>参照した公開情報</h3><span>事実と提案仮説を区別するための参照</span></div><div className="source-list">{sources.map(([name,url,desc],i)=><a key={url} href={url} target="_blank" rel="noreferrer" className="source-item"><span className="source-no">{String(i+1).padStart(2,'0')}</span><span><b>{name}</b><small>{desc}</small></span><ArrowUpRight size={15}/></a>)}</div></div><footer className="reader-footer"><span>日本トレカセンター｜新規事業提案</span><button onClick={()=>window.print()}><Printer size={14}/> PDF保存・印刷</button></footer></section></>}
 <footer className="site-footer"><span>JAPAN TRADING CARD CENTER</span><span>事業仮説の提案｜公開情報は各リンク先を参照</span><button onClick={()=>{setMode(mode==='pitch'?'read':'pitch'); if(mode==='pitch')setTimeout(()=>document.getElementById('appendix')?.scrollIntoView({behavior:'smooth'}),80)}}>補足・出典 <ArrowUpRight size={13}/></button></footer></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);


